# Generated by Django 4.2.2 on 2023-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_alter_language_level_alter_language_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='language',
            field=models.ManyToManyField(related_name='language', to='jobapp.language'),
        ),
    ]
