# Generated by Django 4.2.2 on 2023-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('telephone_number', models.IntegerField(default='no_number')),
                ('email', models.EmailField(max_length=255)),
                ('place', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
