# Generated by Django 4.2.2 on 2023-06-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='userperson',
            old_name='name',
            new_name='first_name',
        ),
    ]
