# Generated by Django 4.2.2 on 2023-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_company_email"),
        ("users", "0003_delete_userprofile_alter_user_email_and_more"),
    ]

    operations = []
