# Generated by Django 4.2.2 on 2023-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_merge_20230628_2012"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=50)),
                ("agent_surname", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=255)),
                ("phone", models.IntegerField(default="no_number")),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
