# Generated by Django 4.2.2 on 2023-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userperson_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
