# Generated by Django 4.2.2 on 2023-06-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_postjob_experience_alter_postjob_language'),
        ('users', '0006_userperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='no_address', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='jobapp.place'),
        ),
    ]
