# Generated by Django 4.2.2 on 2023-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_useragent_area_code_alter_userperson_area_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useragent",
            name="area_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("🇨🇿 Czechia", "🇨🇿 +420"),
                    ("🇸🇰 Slovakia", "🇸🇰 +421"),
                    ("🇨🇭 Switzerland", "🇨🇭 +41"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userperson",
            name="area_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("🇨🇿 Czechia", "🇨🇿 +420"),
                    ("🇸🇰 Slovakia", "🇸🇰 +421"),
                    ("🇨🇭 Switzerland", "🇨🇭 +41"),
                ],
                max_length=20,
            ),
        ),
    ]
