# Generated by Django 4.2.3 on 2023-07-16 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_company_logo_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='company_logos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
