# Generated by Django 4.2.3 on 2023-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_remove_user_area_code_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
