# Generated by Django 4.2.3 on 2023-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_user_company_delete_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_logo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
