# Generated by Django 4.2.3 on 2023-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_user_company_logo_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_logo",
            field=models.ImageField(blank=True, default=1, upload_to="company_logos"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, default=1, upload_to="profile_pics"),
            preserve_default=False,
        ),
    ]
