# Generated by Django 4.2.2 on 2023-07-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_userperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='agent_surname',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='surname',
        ),
    ]
