# Generated by Django 4.2.2 on 2023-07-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_useragent_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_code',
            field=models.CharField(blank=True, choices=[('🇨🇿 Czechia', '🇨🇿 +420'), ('🇸🇰 Slovakia', '🇸🇰 +421'), ('🇨🇭 Switzerland', '🇨🇭 +41')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Companies', to='users.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
