# Generated by Django 4.2.2 on 2023-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_area_code_user_company_user_last_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_surname',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lang_level',
            field=models.CharField(blank=True, choices=[('1', 'A1 - začátečník'), ('2', 'A2 - pokročilý začátečník'), ('3', 'B1 - mírně pokročilý'), ('4', 'B2 - středně pokročilý'), ('5', 'C1 - velmi pokročilý'), ('6', 'C2 - expert')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('NO', 'žádný'), ('ENG', '🇬🇧 angličtina'), ('CHF', '🇨🇭 švýcarská němčina'), ('DEU', '🇩🇪 němčina'), ('FRA', '🇫🇷 francouzština'), ('ITA', '🇮🇹 italština')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
