# Generated by Django 4.2.2 on 2023-07-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ENG', '🇬🇧 angličtina'), ('CHF', '🇨🇭 švýcarská němčina'), ('DEU', '🇩🇪 němčina'), ('FRA', '🇫🇷 francouzština'), ('ITA', '🇮🇹 italština')], max_length=5, null=True),
        ),
    ]
