# Generated by Django 4.2.2 on 2023-06-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shortname", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="PostJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("positions", models.TextField()),
                ("info_position", models.TextField()),
                ("salary", models.IntegerField()),
                ("status", models.BooleanField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postjobs",
                        to="jobapp.place",
                    ),
                ),
            ],
        ),
    ]
