# Generated by Django 4.2.2 on 2023-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_position", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="place",
            old_name="name",
            new_name="name_place",
        ),
    ]
