# Generated by Django 4.2.2 on 2023-06-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0002_position_rename_name_place_name_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="positions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position",
                to="jobapp.position",
            ),
        ),
    ]
