# Generated by Django 4.2.2 on 2023-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0004_alter_place_options_alter_position_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="postjob",
            name="category",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
