# Generated by Django 4.2.2 on 2023-06-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0005_postjob_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("B", "B"),
                    ("C", "C"),
                    ("E", "E"),
                    ("T", "T"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
