# Generated by Django 4.2.2 on 2023-07-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_postjob_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postjobs', to='jobapp.place'),
        ),
    ]
