# Generated by Django 4.2.2 on 2023-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0018_alter_postjob_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="language",
            field=models.CharField(
                choices=[
                    ("NO", "žádný"),
                    ("🇬🇧A1/A2", "🇬🇧 english/beginner"),
                    ("🇬🇧B1/B2", "🇬🇧 english/advanced"),
                    ("🇬🇧C1/C2", "🇬🇧 english/native speaker"),
                    ("🇨🇭A1/A2", "🇨🇭 swiss german/beginner"),
                    ("🇨🇭B1/B2", "🇨🇭 swiss german/advanced"),
                    ("🇨🇭C1/C2", "🇨🇭 swiss german/native speaker"),
                    ("🇩🇪A1/A2", "🇩🇪 germany/beginner"),
                    ("🇩🇪B1/B2", "🇩🇪 germany/advanced"),
                    ("🇩🇪C1/C2", "🇩🇪 germany/native speaker"),
                    ("🇫🇷A1/A2", "🇫🇷 french/beginner"),
                    ("🇫🇷B1/B2", "🇫🇷 french/advanced"),
                    ("🇫🇷C1/C2", "🇫🇷 french/native speaker"),
                    ("🇮🇹A1/A2", "🇮🇹 italy/beginner"),
                    ("🇮🇹B1/B2", "🇮🇹 italy/advanced"),
                    ("🇮🇹C1/C2", "🇮🇹 italy/native speaker"),
                ],
                default="NO",
                max_length=100,
            ),
        ),
    ]
