# Generated by Django 4.2.2 on 2023-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0018_alter_postjob_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NO", "žádný"),
                            ("ENG", "🇬🇧 angličtina"),
                            ("CHF", "🇨🇭 švýcarská němčina"),
                            ("DEU", "🇩🇪 němčina"),
                            ("FRA", "🇫🇷 francouzština"),
                            ("ITA", "🇮🇹 italština"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "A1 - začátečník"),
                            ("2", "A2 - pokročilý začátečník"),
                            ("3", "B1 - mírně pokročilý"),
                            ("4", "B2 - středně pokročilý"),
                            ("5", "C1 - velmi pokročilý"),
                            ("6", "C2 - expert"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="postjob",
            name="language",
        ),
        migrations.AddField(
            model_name="postjob",
            name="language",
            field=models.ManyToManyField(blank=True, to="jobapp.language"),
        ),
    ]
