# Generated by Django 4.2.2 on 2023-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0019_alter_postjob_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="experience",
            field=models.CharField(
                choices=[
                    ("1-3 roky", "1-3"),
                    ("4-6 let", "4-6"),
                    ("6-9 let", "6-9"),
                    ("10 a více let", "10 a více"),
                ],
                default="1-3",
                max_length=100,
            ),
        ),
    ]
