# Generated by Django 4.2.2 on 2023-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0019_language_remove_postjob_language_postjob_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrivingLicence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="postjob",
            name="category",
        ),
        migrations.AddField(
            model_name="postjob",
            name="category",
            field=models.ManyToManyField(blank=True, to="jobapp.drivinglicence"),
        ),
    ]
