# Generated by Django 4.2.2 on 2023-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0019_drivinglicence_language_remove_postjob_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
