# Generated by Django 4.2.2 on 2023-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_alter_drivinglicence_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='state',
            field=models.CharField(choices=[('NO', 'žádný'), ('ENG', '🇬🇧 angličtina'), ('CHF', '🇨🇭 švýcarská němčina'), ('DEU', '🇩🇪 němčina'), ('FRA', '🇫🇷 francouzština'), ('ITA', '🇮🇹 italština')], default='No language prerequisition', max_length=5),
        ),
    ]
