# Generated by Django 4.2.2 on 2023-07-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0021_postjob_accomodation_alter_postjob_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="language",
            field=models.CharField(
                choices=[
                    ("NO", "žádný"),
                    ("🇬🇧A1/A2", "🇬🇧 english-A1/A2"),
                    ("🇬🇧B1/B2", "🇬🇧 english-B1/B2"),
                    ("🇬🇧C1/C2", "🇬🇧 english-C1/C2"),
                    ("🇨🇭A1/A2", "🇨🇭 swiss german-A1/A2"),
                    ("🇨🇭B1/B2", "🇨🇭 swiss german-B1/B2"),
                    ("🇨🇭C1/C2", "🇨🇭 swiss german-C1/C2"),
                    ("🇩🇪A1/A2", "🇩🇪 germany-A1/A2"),
                    ("🇩🇪B1/B2", "🇩🇪 germany-B1/B2"),
                    ("🇩🇪C1/C2", "🇩🇪 germany-C1/C2"),
                    ("🇫🇷A1/A2", "🇫🇷 french-A1/A2"),
                    ("🇫🇷B1/B2", "🇫🇷 french-B1/B2"),
                    ("🇫🇷C1/C2", "🇫🇷 french-C1/C2"),
                    ("🇮🇹A1/A2", "🇮🇹 italy-A1/A2"),
                    ("🇮🇹B1/B2", "🇮🇹 italy-B1/B2"),
                    ("🇮🇹C1/C2", "🇮🇹 italy-C1/C2"),
                ],
                default="NO",
                max_length=100,
            ),
        ),
    ]
