# Generated by Django 4.2.2 on 2023-07-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0021_drivinglicence_licence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postjob",
            name="category",
        ),
        migrations.AddField(
            model_name="postjob",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobapp.drivinglicence",
            ),
            preserve_default=False,
        ),
    ]
