# Generated by Django 4.2.2 on 2023-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0022_remove_postjob_category_postjob_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postjob",
            name="category",
        ),
        migrations.AddField(
            model_name="postjob",
            name="category",
            field=models.ManyToManyField(blank=True, to="jobapp.drivinglicence"),
        ),
    ]
