# Generated by Django 4.2.2 on 2023-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_alter_language_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('1', 'A1 - začátečník'), ('2', 'A2 - pokročilý začátečník'), ('3', 'B1 - mírně pokročilý'), ('4', 'B2 - středně pokročilý'), ('5', 'C1 - velmi pokročilý'), ('6', 'C2 - expert')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='state',
            field=models.CharField(choices=[('ENG', '🇬🇧 angličtina'), ('CHF', '🇨🇭 švýcarská němčina'), ('DEU', '🇩🇪 němčina'), ('FRA', '🇫🇷 francouzština'), ('ITA', '🇮🇹 italština')], default='ENG', max_length=5),
        ),
    ]
