# Generated by Django 4.2.2 on 2023-07-06 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0023_alter_postjob_accomodation_alter_postjob_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postjob",
            old_name="accomodation",
            new_name="accommodation",
        ),
    ]
