# Generated by Django 4.2.2 on 2023-07-02 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0023_remove_postjob_category_postjob_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postjob",
            old_name="category",
            new_name="driving_licence",
        ),
    ]
