# Generated by Django 4.2.2 on 2023-07-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0024_rename_category_postjob_driving_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="postjob",
            name="accommodation",
            field=models.CharField(
                choices=[
                    ("vlastní ubytování", "vlastní"),
                    ("zajištěné ubytování", "zajištěné"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
