# Generated by Django 4.2.2 on 2023-07-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_rename_accomodation_postjob_accommodation'),
        ('jobapp', '0024_rename_category_postjob_driving_licence'),
    ]

    operations = [
    ]
