# Generated by Django 4.2.2 on 2023-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_merge_20230707_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='drivinglicence',
            name='licence',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='driving_licence',
        ),
        migrations.AddField(
            model_name='postjob',
            name='category',
            field=models.CharField(blank=True, choices=[('', '---------'), ('AM', 'AM 🛵'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A 🏍️'), ('B1', 'B1 🚚'), ('B', 'B 🚗'), ('C1', 'C1 🚛'), ('C', 'C'), ('D1', 'D1 🚐'), ('D', 'D 🚌'), ('BE', 'BE '), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('DE', 'DE'), ('T', 'T 🚜')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postjob',
            name='licence',
            field=models.CharField(choices=[('', '---------'), ('AM', 'AM 🛵'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A 🏍️'), ('B1', 'B1 🚚'), ('B', 'B 🚗'), ('C1', 'C1 🚛'), ('C', 'C'), ('D1', 'D1 🚐'), ('D', 'D 🚌'), ('BE', 'BE '), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('DE', 'DE'), ('T', 'T 🚜')], max_length=6, null=True),
        ),
    ]
