# Generated by Django 4.2.2 on 2023-07-07 19:12

from django.db import migrations, models
import jobapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0026_alter_postjob_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postjob",
            name="language",
        ),
        migrations.AddField(
            model_name="postjob",
            name="language",
            field=models.CharField(
                blank=True, max_length=50, verbose_name=jobapp.models.Language
            ),
        ),
    ]
