# Generated by Django 4.2.2 on 2023-07-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_postjob_accommodation'),
        ('jobapp', '0026_delete_language_remove_drivinglicence_licence_and_more'),
    ]

    operations = [
    ]
