# Generated by Django 4.2.2 on 2023-07-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0027_remove_postjob_language_postjob_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postjob",
            name="language",
        ),
        migrations.AddField(
            model_name="postjob",
            name="language",
            field=models.ManyToManyField(blank=True, to="jobapp.language"),
        ),
    ]
