# Generated by Django 4.2.2 on 2023-07-16 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0028_positioncategory_position_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="category",
        ),
        migrations.DeleteModel(
            name="PositionCategory",
        ),
    ]
