# Generated by Django 4.2.2 on 2023-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0028_positioncategory_alter_position_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postjob",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("plný", "Plný úvazek"),
                    ("částečný", "Částečný úvazek"),
                    ("brigáda", "Brigáda"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
