# Generated by Django 4.2.3 on 2023-07-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0028_positioncategory_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='position_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='position_category', to='jobapp.positioncategory'),
        ),
    ]
