# Generated by Django 4.2.2 on 2023-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0028_language_remove_postjob_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='accommodation',
            field=models.CharField(choices=[('vlastní ubytování', 'vlastní'), ('zajištěné ubytování', 'zajištěné')], default='', max_length=30, null=True),
        ),
    ]
