# Generated by Django 4.2.2 on 2023-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0029_remove_position_category_delete_positioncategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="postjob",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postjob",
            name="status",
            field=models.CharField(
                choices=[("active", "Aktivní"), ("archived", "Archivovaný")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="postjob",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
