# Generated by Django 4.2.3 on 2023-07-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_postjob_position_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='position_category',
        ),
    ]
