# Generated by Django 4.2.3 on 2023-07-18 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_postjob_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='jobapp.positioncategory'),
            preserve_default=False,
        ),
    ]
