# Generated by Django 4.2.3 on 2023-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_rename_positions_postjob_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinglicence',
            name='licence',
        ),
        migrations.AddField(
            model_name='drivinglicence',
            name='licence_category',
            field=models.CharField(default='', max_length=6),
        ),
    ]
