# Generated by Django 4.2.3 on 2023-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_drivinglicence_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='diet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='salary',
            field=models.IntegerField(default=30),
        ),
    ]
