# Generated by Django 4.2.3 on 2023-07-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0036_alter_postjob_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positioncategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Position Categories'},
        ),
        migrations.RemoveField(
            model_name='drivinglicence',
            name='short_name',
        ),
    ]
