# Generated by Django 4.2.2 on 2023-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0037_alter_positioncategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="accommodation",
            field=models.CharField(
                choices=[
                    ("vlastní ubytování", "mám zajištěné"),
                    ("zajištěné ubytování", "chci zajistit"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
