# Generated by Django 4.2.3 on 2023-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0038_alter_postjob_accommodation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postjob",
            name="language",
            field=models.ManyToManyField(
                blank=True, related_name="language", to="jobapp.language"
            ),
        ),
    ]
