# Generated by Django 4.2.3 on 2023-08-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
