# Generated by Django 4.2.3 on 2023-08-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobapp", "0038_alter_postjob_accommodation"),
        ("message", "0002_message_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="job",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobapp.postjob",
            ),
            preserve_default=False,
        ),
    ]
