# Generated by Django 4.2.3 on 2023-08-10 21:43

import django.core.validators
from django.db import migrations, models
import message.validators


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_alter_message_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    message.validators.validate_file_size,
                ],
            ),
        ),
    ]
